version: '2'

services:
  web:
    build: .
    restart: always
  tor:
    image: strm/tor
    restart: always
    depends_on:
      - web
    environment:
        LISTEN_PORT: 80
        REDIRECT: web:80
        # tornaw7ltlqw544t.onion
        PRIVATE_KEY: |
          -----BEGIN RSA PRIVATE KEY-----
          ...
          -----END RSA PRIVATE KEY-----